### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[66,4,4] = 3406 is not in [0, 3406)

### ISSUE THREAD

**Issue by loveJasmine** [heshenghuan/LSTM-NER#6]
Iter 348: mini-batch loss=13.606838, acc=0.966827
Iter 349: mini-batch loss=14.193445, acc=0.964598
Iter 350: mini-batch loss=13.139592, acc=0.969806
[+] Model saved in file: /Users/LSTM-NER/models/14:54:24-2017-10-09/-350
----------2017-10-09 15:09:39----------
Iter 350: valid loss(avg)=17.923138, acc(avg)=0.955858
round 49: max_acc=0.955857631375 BestIter=350

Optimization Finished!
Traceback (most recent call last):
  File "main.py", line 348, in <module>
    tf.app.run()
  File "/Library/Python/2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 331, in main
    FLAGS)
  File "/Users/LSTM-NER/model.py", line 285, in run
    [self.transition, cost, pred], feed_dict=test)
  File "/Library/Python/2.7/site-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/Library/Python/2.7/site-packages/tensorflow/python/client/session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "/Library/Python/2.7/site-packages/tensorflow/python/client/session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "/Library/Python/2.7/site-packages/tensorflow/python/client/session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[66,4,4] = 3406 is not in [0, 3406)
	 [[Node: embedding_lookup = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@embeddings"], validate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](embeddings/read, _recv_inputs/X_placeholder_0)]]

Caused by op u'embedding_lookup', defined at:
  File "main.py", line 348, in <module>
    tf.app.run()
  File "/Library/Python/2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 331, in main
    FLAGS)
  File "/Users/LSTM-NER/model.py", line 185, in run
    pred = self.inference(self.X, self.X_len)
  File "/Users/LSTM-NER/model.py", line 318, in inference
    word_vectors = tf.nn.embedding_lookup(self.emb_matrix, X)
  File "/Library/Python/2.7/site-packages/tensorflow/python/ops/embedding_ops.py", line 119, in embedding_lookup
    params[0], ids, validate_indices=validate_indices, name=name))
  File "/Library/Python/2.7/site-packages/tensorflow/python/ops/embedding_ops.py", line 41, in _do_gather
    params, ids, name=name, validate_indices=validate_indices)
  File "/Library/Python/2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1207, in gather
    validate_indices=validate_indices, name=name)
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): indices[66,4,4] = 3406 is not in [0, 3406)
	 [[Node: embedding_lookup = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@embeddings"], validate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](embeddings/read, _recv_inputs/X_placeholder_0)]]

**Comment by heshenghuan** [comment]
It maybe caused by an invalid index. But I have no idea about this now.

**Comment by heshenghuan** [comment]
@loveJasmine 
Hi, loveJasmine.
I think I find the reason of your problem. It is because an incorrect lookup dictionary used to load the embedding matrix. It should use the dictionary **'feats2idx'**, i.e. the context feature dictionary (because the feature extractor used non-suffix setting), but not the **'words2idx'** to load the embedding.

And I think this problem should be solved now, after updates for ver 0.2.1.
